<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Курсовой_проект</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="изображения и спрайты\героиня меню.png" />
    <None Remove="изображения и спрайты\фон.jpg" />
    <None Remove="изображения и спрайты\чиби героиня.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="изображения и спрайты\фон.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="изображения и спрайты\героиня меню.png" />
    <Resource Include="изображения и спрайты\чиби героиня.png" />
  </ItemGroup>

</Project>
